scratch file for testing Fisher information matrix code

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from data_objects import Fluorophore, get_fluorophore_list
from imaging_model import form_illumination_df, calc_A_entry, form_A
from information_matrix import read_qe, form_q_vec, FIM, fast_form_q_vec

In [2]:
fluorophore_list = get_fluorophore_list()
list(map(Fluorophore.get_name, fluorophore_list))

['mCherry', 'mEmerald', 'mNeptune2.5', 'mTagBFP2']

In [3]:
qe = read_qe((400,900))
qe

400    0.708963
401    0.713369
402    0.717774
403    0.720846
404    0.723723
         ...   
895    0.333867
896    0.331035
897    0.328203
898    0.325371
899    0.322539
Length: 500, dtype: float64

In [4]:
illumination_data = pd.DataFrame({
    "wavelength" : [405, 488, 561, 637],
    "k"          : [1,   1,   1,   1]
})
print(illumination_data)
wavelength_range = (400,900)
bin_width = 10
illumination_df = form_illumination_df(illumination_data, wavelength_range, bin_width)
illumination_df

   wavelength  k
0         405  1
1         488  1
2         561  1
3         637  1


illumination_wavelength  bin_wavelength_min  bin_wavelength_max  k
0                        405                 400                 410  1
1                        405                 410                 420  1
2                        405                 420                 430  1
3                        405                 430                 440  1
4                        405                 440                 450  1
..                       ...                 ...                 ... ..
195                      637                 850                 860  1
196                      637                 860                 870  1
197                      637                 870                 880  1
198                      637                 880                 890  1
199                      637                 890                 900  1

[200 rows x 4 columns]

In [5]:
q_vec = form_q_vec(illumination_df, qe)
q_vec

array([0.72660005, 0.75536952, 0.782749  , 0.80398895, 0.82522891,
       0.84646887, 0.85963479, 0.87264099, 0.88564719, 0.89865338,
       0.90970199, 0.91858668, 0.92747137, 0.93635605, 0.94524074,
       0.94992281, 0.94740548, 0.94488815, 0.94237083, 0.9398535 ,
       0.93530398, 0.93043173, 0.92555949, 0.9169729 , 0.9072074 ,
       0.8974419 , 0.88391718, 0.86975721, 0.85545014, 0.83845818,
       0.82146621, 0.80447424, 0.78713305, 0.76270016, 0.7359505 ,
       0.70479856, 0.67497506, 0.647704  , 0.62043294, 0.59316189,
       0.56458121, 0.5385968 , 0.51657018, 0.49454356, 0.47251693,
       0.44761165, 0.4221237 , 0.39272212, 0.36251418, 0.33386697,
       0.72660005, 0.75536952, 0.782749  , 0.80398895, 0.82522891,
       0.84646887, 0.85963479, 0.87264099, 0.88564719, 0.89865338,
       0.90970199, 0.91858668, 0.92747137, 0.93635605, 0.94524074,
       0.94992281, 0.94740548, 0.94488815, 0.94237083, 0.9398535 ,
       0.93530398, 0.93043173, 0.92555949, 0.9169729 , 0.90720

In [19]:
N_ex = len(illumination_data['wavelength'])
form_q_vec(illumination_df, qe) - fast_form_q_vec(qe,  wavelength_range, bin_width, N_ex)
#fast_form_q_vec(qe,  wavelength_range, bin_width, N_ex)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
qe[(illumination_df.bin_wavelength_min + illumination_df.bin_wavelength_max)/2]

405    0.726600
415    0.755370
425    0.782749
435    0.803989
445    0.825229
         ...   
855    0.447612
865    0.422124
875    0.392722
885    0.362514
895    0.333867
Length: 200, dtype: float64

In [8]:
A = form_A(illumination_df, fluorophore_list)
A

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 7.35714057e-05],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.16754622e-03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 6.15334177e-03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.50190761e-02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 6.41356063e-02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 9.34084958e-02],
       [0.00000000e+00, 5.87826800e-05, 0.00000000e+00, 8.69214170e-02],
       [0.00000000e+00, 3.82946816e-04, 0.00000000e+00, 7.28650135e-02],
       [0.00000000e+00, 2.21769978e-03, 0.00000000e+00, 5.93417362e-02],
       [0.00000000e+00, 8.29179547e-03, 0.00000000e+00, 4.36518342e-02],
       [0.00000000e+00, 1.78469029e-02, 0.00000000e+00, 3.04356375e-02],
       [0.00000000e+00, 1.87451435e-02, 0.00000000e+00, 2.12232180e-02],
       [0.00000000e+00, 1.21533477e-02, 0.00000000e+00, 1.47388049e-02],
       [0.00000000e+00, 8.80273498e-03, 0.00000000e

In [9]:
np.shape(A.T)

(4, 200)

In [10]:
x_vec = np.array([1,1,1,1])
print(x_vec)
print(A @ x_vec)

[1 1 1 1]
[7.35714057e-05 1.16754622e-03 6.15334177e-03 2.50190761e-02
 6.41356063e-02 9.34084958e-02 8.69801997e-02 7.32479604e-02
 6.15594360e-02 5.19436297e-02 4.82825404e-02 3.99683615e-02
 2.68921527e-02 1.87935186e-02 1.36975742e-02 9.43686526e-03
 6.17683539e-03 4.10642572e-03 2.93474260e-03 2.32437901e-03
 1.97740675e-03 1.74686899e-03 1.57649819e-03 1.47610680e-03
 1.38284819e-03 1.15650277e-03 1.03619079e-03 9.03912019e-04
 7.76932992e-04 6.35773008e-04 3.70135757e-04 2.75511959e-04
 2.17428431e-04 1.74480406e-04 1.41538519e-04 1.12896545e-04
 8.78900733e-05 6.82400388e-05 5.26699294e-05 4.05170900e-05
 2.47563441e-05 1.92668586e-05 1.60827837e-05 1.39586424e-05
 1.18515969e-05 7.56484909e-07 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 3.38781012e-04 2.20702951e-03 1.27812236e-02 4.77879344e-02
 1.02856689e-01 1.08033500e-01 7.00431392e-02 5.07326216e-02
 4.07019300e-0

In [11]:
r = np.array([
    [0,-1],
    [1,0]
])
print(r)
print(r*r)
print(r@r)

[[ 0 -1]
 [ 1  0]]
[[0 1]
 [1 0]]
[[-1  0]
 [ 0 -1]]


In [12]:
M = np.array([[1, 3], [4, 2], [5,5]])
v = np.array([10, 0.5])
print(M @ np.diag(v))
print(M * v)

[[10.   1.5]
 [40.   1. ]
 [50.   2.5]]
[[10.   1.5]
 [40.   1. ]
 [50.   2.5]]


In [13]:
v*v

array([100.  ,   0.25])

In [14]:
y_bar = A @ x_vec
variance_vec = y_bar + 2
inverse_variance_vec = 1/variance_vec
diag_vec = q_vec*q_vec * inverse_variance_vec * (1 + inverse_variance_vec/2)
F = (A.T * diag_vec) @ A
np.array(F)

array([[6.29050685e-04, 2.05565755e-05, 5.27121623e-04, 7.34841296e-07],
       [2.05565755e-05, 1.82743267e-02, 1.20272316e-05, 9.22671681e-04],
       [5.27121623e-04, 1.20272316e-05, 8.14698416e-04, 4.66128359e-07],
       [7.34841296e-07, 9.22671681e-04, 4.66128359e-07, 1.48949344e-02]])

In [15]:
np.linalg.inv(np.array(F))

array([[ 3.47238547e+03, -2.42991678e+00, -2.24664763e+03,
         4.95194749e-02],
       [-2.42991678e+00,  5.48954967e+01,  7.63725381e-01,
        -3.40042389e+00],
       [-2.24664763e+03,  7.63725381e-01,  2.68105022e+03,
        -2.03728234e-02],
       [ 4.95194749e-02, -3.40042389e+00, -2.03728234e-02,
         6.73475574e+01]])

In [16]:
F = FIM(A, x_vec, q_vec, 2)
F

array([[6.29050685e-04, 2.05565755e-05, 5.27121623e-04, 7.34841296e-07],
       [2.05565755e-05, 1.82743267e-02, 1.20272316e-05, 9.22671681e-04],
       [5.27121623e-04, 1.20272316e-05, 8.14698416e-04, 4.66128359e-07],
       [7.34841296e-07, 9.22671681e-04, 4.66128359e-07, 1.48949344e-02]])

In [17]:
print(A.shape)

(200, 4)


In [18]:
F_test = np.zeros((4,4))
for j in range(4):
    for k in range(4):
        for i in range(A.shape[0]):
            F_test[j,k] += (q_vec[i]**2 / variance_vec[i]) * A[i,j] * A[i,k]
            F_test[j,k] += 0.5 * (q_vec[i]**2 / (variance_vec[i]**2)) * A[i,j] * A[i,k]
print(F_test)
print(np.abs(F - F_test))

[[6.29050685e-04 2.05565755e-05 5.27121623e-04 7.34841296e-07]
 [2.05565755e-05 1.82743267e-02 1.20272316e-05 9.22671681e-04]
 [5.27121623e-04 1.20272316e-05 8.14698416e-04 4.66128359e-07]
 [7.34841296e-07 9.22671681e-04 4.66128359e-07 1.48949344e-02]]
[[0.00000000e+00 1.35525272e-20 0.00000000e+00 0.00000000e+00]
 [1.35525272e-20 1.73472348e-17 1.69406589e-21 2.16840434e-19]
 [1.08420217e-19 1.69406589e-21 0.00000000e+00 0.00000000e+00]
 [1.05879118e-22 1.08420217e-19 0.00000000e+00 3.46944695e-18]]
