just a scratch file for testing .py file code

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from data_objects import Fluorophore, get_fluorophore_list
from imaging_model import form_illumination_df, calc_A_entry, form_A, fast_form_A

In [2]:
illumination_data = pd.DataFrame({
    "wavelength" : [405, 488, 561, 637],
    "k"          : [1,   1,   1,   1]
})
print(illumination_data)
wavelength_range = (400,900)
bin_width = 10
illumination_df = form_illumination_df(illumination_data, wavelength_range, bin_width)
illumination_df

   wavelength  k
0         405  1
1         488  1
2         561  1
3         637  1


illumination_wavelength  bin_wavelength_min  bin_wavelength_max  k
0                        405                 400                 410  1
1                        405                 410                 420  1
2                        405                 420                 430  1
3                        405                 430                 440  1
4                        405                 440                 450  1
..                       ...                 ...                 ... ..
195                      637                 850                 860  1
196                      637                 860                 870  1
197                      637                 870                 880  1
198                      637                 880                 890  1
199                      637                 890                 900  1

[200 rows x 4 columns]

In [3]:
illumination_df_row = illumination_df.loc[0]
illumination_df_row
illumination_wavelength = illumination_df_row.illumination_wavelength
print(illumination_wavelength)
type(illumination_wavelength)

405


numpy.int64

In [4]:
illumination_data = pd.DataFrame({
    "wavelength" : [405, 488, 561, 637],
    "k"          : [1,   1,   1,   1]
})
print(illumination_data)
wavelength_range = (400,900)
bin_width = 10

illumination_df = form_illumination_df(illumination_data, wavelength_range, bin_width)
fluorophore_list = get_fluorophore_list(wavelength_range=wavelength_range)
print(list(map(Fluorophore.get_name, fluorophore_list)))

form_A(illumination_df, fluorophore_list)

   wavelength  k
0         405  1
1         488  1
2         561  1
3         637  1
['mCherry', 'mEmerald', 'mNeptune2.5', 'mTagBFP2']


array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 7.35714057e-05],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.16754622e-03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 6.15334177e-03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.50190761e-02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 6.41356063e-02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 9.34084958e-02],
       [0.00000000e+00, 5.87826800e-05, 0.00000000e+00, 8.69214170e-02],
       [0.00000000e+00, 3.82946816e-04, 0.00000000e+00, 7.28650135e-02],
       [0.00000000e+00, 2.21769978e-03, 0.00000000e+00, 5.93417362e-02],
       [0.00000000e+00, 8.29179547e-03, 0.00000000e+00, 4.36518342e-02],
       [0.00000000e+00, 1.78469029e-02, 0.00000000e+00, 3.04356375e-02],
       [0.00000000e+00, 1.87451435e-02, 0.00000000e+00, 2.12232180e-02],
       [0.00000000e+00, 1.21533477e-02, 0.00000000e+00, 1.47388049e-02],
       [0.00000000e+00, 8.80273498e-03, 0.00000000e

now, we test fast_form_A

In [5]:
illumination_data = pd.DataFrame({
    "wavelength" : [405, 488, 561, 637],
    "k"          : [1,   1,   1,   1]
})
illumination_wavelengths = np.array(illumination_data['wavelength'])
k = np.array(illumination_data['k'])
wavelength_range = (400,900)
bin_width = 10
fluorophore_list = get_fluorophore_list(wavelength_range=wavelength_range)
params = (illumination_wavelengths, k, wavelength_range, bin_width, fluorophore_list)

spacer

In [6]:
bins_list = np.arange(*wavelength_range, bin_width)
bins_list

array([400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520,
       530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640, 650,
       660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770, 780,
       790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890])

In [7]:
N_ex = len(illumination_wavelengths)
N_em = len(bins_list)
idx = np.arange(N_ex*N_em)

In [13]:
illumination_wavelengths = illumination_wavelengths[idx // N_em]
k = k[idx // N_em]
bins_list = bins_list[idx % N_em]
idx // N_em

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3], dtype=int32)

In [9]:
i = 0
fluorophore = fluorophore_list[i]
column_excitation = np.array(fluorophore.spectra.excitation[illumination_wavelengths])
fluorophore_emission_array = np.array(fluorophore.spectra.emission.loc[wavelength_range[0] : wavelength_range[1]-1])
column_emission = np.trapz(fluorophore_emission_array.reshape(N_em,bin_width))[idx % N_em]

k * fluorophore.brightness * column_excitation * column_emission

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.42803182e-06,
       1.05912360e-05, 3.40028309e-05, 1.35160890e-04, 3.29521246e-04,
       4.90018091e-04, 4.99416398e-04, 4.09940916e-04, 3.28078702e-04,
       2.74739391e-04, 2.35770376e-04, 1.99651620e-04, 1.66505028e-04,
       1.31013212e-04, 1.00397603e-04, 7.77783918e-05, 6.10164329e-05,
       4.83818343e-05, 3.87832545e-05, 3.14079926e-05, 2.52169522e-05,
       1.98705404e-05, 1.58331577e-05, 1.25591335e-05, 9.80465752e-06,
       4.84718119e-07, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
      

In [10]:
fast_form_A(*params)

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 7.35714057e-05],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.16754622e-03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 6.15334177e-03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.50190761e-02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 6.41356063e-02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 9.34084958e-02],
       [0.00000000e+00, 5.87826800e-05, 0.00000000e+00, 8.69214170e-02],
       [0.00000000e+00, 3.82946816e-04, 0.00000000e+00, 7.28650135e-02],
       [0.00000000e+00, 2.21769978e-03, 0.00000000e+00, 5.93417362e-02],
       [0.00000000e+00, 8.29179547e-03, 0.00000000e+00, 4.36518342e-02],
       [0.00000000e+00, 1.78469029e-02, 0.00000000e+00, 3.04356375e-02],
       [0.00000000e+00, 1.87451435e-02, 0.00000000e+00, 2.12232180e-02],
       [0.00000000e+00, 1.21533477e-02, 0.00000000e+00, 1.47388049e-02],
       [0.00000000e+00, 8.80273498e-03, 0.00000000e

In [11]:
A_1 = form_A(illumination_df, fluorophore_list)
A_2 = fast_form_A(*params)

print(A_1 - A_2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0.